# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Download Test
  description: download
  version: "1.0.0"
# the domain of the service
host: api.uber.com
# array of all schemes that your API supports
schemes:
  - https
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json

paths:
  /file:
    get:
      produces:
        - application/octet-stream

      responses:
        200:
          description: download a file
          schema:
            type: file

        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    post:
      produces:
        - application/json

      consumes:
        - multipart/form-data

      parameters:
        - name: attachment
          in: formData
          type: file
          required: true

      responses:
        201:
          description: The attachment has been uploaded.

        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
